import type { Metadata } from "next";
import "@/styles/globals.css";
import ErrorPopup from "@/components/ErrorPopup";

export const metadata: Metadata = {
  title: "Social Network",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          {children}
          <ErrorPopup />
      </body>
    </html>
  );
}
