import type { Metadata } from "next";
import "./globals.css";
import { ErrorProvider } from "@/context/ErrorContext";

export const metadata: Metadata = {
  title: "Social Network",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ErrorProvider>{children}</ErrorProvider>
      </body>
    </html>
  );
}
